### PR TITLE
Upgrade baragon to 0.4.0

### PR DESCRIPTION
**Pull request by eherot**

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
@eherot may as well while you’re in there! Anything breaking between 0.1.7 & 0.4.0?

**Comment by eherot** [comment]
lol [who knows](https://github.com/HubSpot/Baragon/compare/Baragon-0.1.7...Baragon-0.4.0). Presumably they've run it with the latest version of Singularity...

**Comment by eherot** [comment]
Also I was able to run it with our config file.

**Comment by jeffbyrnes** [comment]
That last point seems most important. Bear in mind, you’ll need to coordinate this with the `BaragonService` that’s installed on the Singularity boxes.

**Comment by jeffbyrnes** [comment]
In point of fact, I bring to your attention [Baragon 0.2.0 release notes](https://github.com/HubSpot/Baragon/releases/tag/Baragon-0.2.0)

**Comment by jeffbyrnes** [comment]
Also, generally, it’s easier to read their [release notes](https://github.com/HubSpot/Baragon/releases) then try to parse the commit log :)

**Comment by jeffbyrnes** [comment]
Then again, how about this one: https://github.com/HubSpot/Baragon/releases/tag/Baragon-0.1.11:

> Due to changes in the way upstreams are stored in zookeeper, for this release it is recommended that you first upgrade all `BaragonAgentService` instances before upgrading `BaragonService`

Starting to feel like a catch-22 when combined w/ the 0.2.0 release notes…

**Comment by jeffbyrnes** [comment]
By the way, and this is kinda awesome, but Baragon has [ELB Sync](https://github.com/HubSpot/Baragon/blob/master/docs/managing_baragon.md#elb), which lets it (de)register LB instances on an associated ELB. That sounds _very_ nifty.

**Comment by eherot** [comment]
@ssalinas seems to think we're safe as long as we do the agents first.

**Comment by eherot** [comment]
If he's wrong NBD we'll just have to hold him personally responsible for all corporate losses.

**Comment by ssalinas** [comment]
The `BaragonService` recommendation for 0.2.0 can be reversed if needed. In that particular case, new functionality of multiple domain support won't work until both are upgraded.

The zk data migrations in `0.1.9` and `0.1.11` are the two I was taking a closer look at. One changes the way old request data is stored, and should be fine for an upgrade in either order. `0.1.11` is what requires agents first, since the way upstream data is recorded gets changed. The agents are able to read both the new and old versions of the data. But and un-upgraded agent might run into errors reading upstream info if service is upgraded first.

**Pull request merged**
